name = "RecurrenceMicrostates"
uuid = "cb83a08b-85c6-4e94-91aa-4e946c7d4f0c"
authors = ["G. V. Ferreira", "T. L. Prado and S. R. Lopes"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
